version: '3.4'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  nginx:
    <<: *restart_policy
    image: user12/nginx:mainline
    build:
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      mykey: "$mykey"
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
    networks:
      - front

networks:
  front:
    driver: bridge
